name: ceo_events
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_riverpod: ^0.12.1
  dio: ^3.0.10
  http: ^0.12.2
  shimmer: ^1.0.1
  # bottom_navy_bar: ^5.2.0
  google_fonts: ^1.1.0
  # loadinglistview: ^0.0.2
  # infinite_listview: ^1.0.1+1
  # flutter_staggered_animations: "^0.1.2"
  intl: ^0.16.1
  # cloud_firestore: ^0.9.13
  animations: ^1.1.0
  sliver_fab: "^1.0.0"
  flashy_tab_bar: ^0.0.3
  palette_generator: ^0.2.3
  bubble_tab_indicator: ^0.1.4
  tab_indicator_styler: ^1.0.0
  cached_network_image: ^2.3.3
  flutter_svg: ^0.19.1
  page_indicator: ^0.3.0
  rect_getter: ^0.1.0
  flare_flutter: ^1.5.5
  date_format: ^1.0.9
  url_launcher: ^5.7.10
  font_awesome_flutter: ^8.10.0
  carousel_slider: ^2.3.1
  photo_view: ^0.10.3
  # path_provider: ^1.6.24
  image_picker_saver: ^0.3.0
  esys_flutter_share: ^1.0.2
  # downloads_path_provider_28: ^0.1.0
  open_file: ^3.0.1
  flutter_local_notifications: ^1.3.0
  path: ^1.7.0
  path_provider: ^1.6.24
  flutter_cache_manager: ^2.0.0
  share:
    git:
      url: git://github.com/himanshusharma89/plugins.git
      path: packages/share
  # share: ^0.6.5+4
  flutter_barcode_scanner: ^1.0.1
  flutter_progress_dialog: ^0.1.0
  sliding_card: ^0.1.2
  google_maps_flutter: ^1.0.6
  image_gallery_saver: ^1.6.7
  permission_handler: ^5.0.1+1
  fluttertoast: ^7.1.5
  socket_io_client: ^0.9.11
  shared_preferences: ^0.5.8
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  get_it: ^4.0.4
  scrollable_positioned_list: ^0.1.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# downloads_path_provider_28:
#     path: ../
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  fonts:
    - family:  HotelBookingConcept
      fonts:
        - asset: fonts/HotelBookingConcept.ttf
  assets:
    - assets/
    - assets/logo.png
    - assets/businessman.png
    - assets/businessman1.png
    - assets/businessman2.png
    - assets/profile-user.png
    - assets/profile.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
